#!/bin/bash -l
# Queue to use
#PBS -q default
# NAME of job
#PBS -N sync
# Account resources to use
#PBS -A DBIC
# Resources to reserve
#PBS -l nodes=2:ppn=4
#PBS -l walltime=16:00:00
# Send email to this address
#PBS -M emtempleton@gmail.com
# When to send defined here
#PBS -m ea
# Change to job working directory
cd $PBS_O_WORKDIR
##############################
# Enter your code to run below
##############################
python get_article_links.py
