language: python

python:
  - "3.6"

install:
  - pip install codecov flake8 pytest bs4 ipython pandas

script:
  - flake8 topic_modeling/scrape_training_data/*.py
  - pytest topic_modeling/scrape_training_data/*.py

after_success:
  - codecov
