language: python

python:
  - "3.6"

install:
  - pip install codecov flake8 pytest bs4 ipython pandas nltk sklearn

script:
  - flake8 topic_modeling/scrape_training_data/*.py
  - pytest topic_modeling/scrape_training_data/*.py
  - flake8 topic_modeling/train_models/*.py
  - pytest topic_modeling/train_models/*.py
  - flake8 topic_modeling/validate_models/*.py
  - pytest topic_modeling/validate_models/*.py
  - flake8 topic_modeling/*.py
  - pytest topic_modeling/*.py

after_success:
  - codecov
