#!/bin/bash -l
# Queue to use
#PBS -q default
# NAME of job
#PBS -N sync
# Account resources to use
#PBS -A DBIC
# Resources to reserve
#PBS -l nodes=2:ppn=4
#PBS -l walltime=24:00:00
#PBS -t 25,30,35,40,45,55,60,70,80,90,100,150,200
# Send email to this address
#PBS -M emtempleton@gmail.com
# When to send defined here
#PBS -m ea
# Change to job working directory
cd $PBS_O_WORKDIR
##############################
# Enter your code to run below
##############################
~/.conda/envs/python3/bin/python evaluate_the_dartmouth_similarTopics.py ${PBS_ARRAYID}
